name: Daily Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Everyday at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make tar xorriso binutils

      - name: Run build script
        run: ./tools/build.sh

      - name: Archive ISO
        uses: actions/upload-artifact@v2
        with:
          name: Paradox-Public-$(date +'%Y%m%d').iso
          path: image.iso
