name: Daily Build (Rewrite)

on:
  push:
    branches:
      - rewrite
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=iso_date::$(date +'%Y-%m-%d')"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Initialize and update submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make tar xorriso binutils nasm

      - name: Run build script
        run: ./tools/build.sh

      - name: Archive ISO
        uses: actions/upload-artifact@v2
        with:
          name: Paradox-Public-${{ steps.date.outputs.iso_date }}.iso
          path: image.iso
